---
# tasks file for backup

- name: configure time
  copy: 
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
  notify: 
    - restart_chron
    
- name: install epel
  yum:
    name: epel-release
    state: present
    
- name: install borgbackup
  yum:
    name: borgbackup
    state: present
    
- name: add user
  user:
    name: borg
    
- name: mount disk
  ansible.posix.mount:
    path: /var/backup/
    src: /dev/sdb/
    fstype: tmpfs
    state: mounted
    
- name: change owner
  ansible.builtin.file:
    path: /var/backup
    owner: borg
        
- name: give insecure permissions to an directory
  ansible.builtin.file:
    path: /home/borg/.ssh/
    owner: borg
    mode: '0700'
    state: directory
       
#- name: create file for ssh-key
#  shell: touch /home/borg/.ssh/authorized_keys
  
- name: give insecure permissions to an existing file
  ansible.builtin.file:
    path: /home/borg/.ssh/authorized_keys
    owner: borg
    mode: '0600'
    state: touch
   
#- name: post install
#  shell: chown borg:borg /var/backup && mkdir /home/borg/.ssh && touch /home/borg/.ssh/authorized_keys && chmod 700 /home/borg/.ssh && chmod 600 /home/borg/.ssh/authorized_keys

  
 
