---
# tasks file for client
- name: configure time
  copy: 
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
  notify: 
    - restart_chron
    
- name: install epel
  yum:
    name: epel-release
    state: present
    
- name: install borgbackup
  yum:
    name: borgbackup
    state: present
    
- name: copy files
  copy:
    src: borg-backup.service
    dest: /etc/systemd/system/
    
- name: copy files
  copy:
    src: borg-backup.timer
    dest: /etc/systemd/system/
